export const Users = [
{
    id:1,
    profilePicture: "assets/khushi.PNG",
    username: "Khushi Maru",
},
{
    id:2,
    profilePicture: "assets/rid.PNG",
    username: "Ridhi Jain",
},
{
    id:3,
    profilePicture: "assets/v.jpg",
    username: "Vidushi Ajmera",
},
{
    id:4,
    profilePicture: "assets/t2.PNG",
    username: "Ridhi Jain",
},
{
    id:5,
    profilePicture: "assets/kat.PNG",
    username: "Krati Jain",
},
{
    id:6,
    profilePicture: "assets/trio.PNG",
    username: "Ridhi Jain",
},
{
    id:7,
    profilePicture: "assets/m.PNG",
    username: "Mayur Dewani",
},
{
    id:8,
    profilePicture: "assets/r.PNG",
    username: "Rudransh Joshi",
},
{
    id:9,
    profilePicture: "assets/v2.JPG",
    username: "Vidushi Ajmera",
},
{
    id:10,
    profilePicture: "assets/m2.PNG",
    username: "Mayur Dewani",
},
{
    id:11,
    profilePicture: "assets/4r.PNG",
    username: "MAD HOUSE ",
},
{
    id:12,
    profilePicture: "assets/v3.PNG",
    username: "Vidushi Ajmera ",
},
{
    id:13,
    profilePicture: "assets/a.jpg",
    username: "Akshay Vijayvargiya ",
},


];

export const Posts=[
    {
        id:1,
        desc:"Sunday Morning",
        photo:"assets/khushi.PNG",
        date:"5 min ago",
        userId:1,
        likes : 28,
        comments: "9 comments",
    },
    {
        id:2,
        desc:"Sunday Morning",
        photo:"assets/rid.PNG",
        date:"10 min ago",
        userId:2,
        likes : 208,
        comments: "22comments",
    },
    {
        id:3,
        desc:"Sunday Morning",
        photo:"assets/v.jpg",
        date:"15 min ago",
        userId:3,
        likes : 148,
        comments:"4comments",
    },
    {
        id:4,
        desc:"Sunday Morning",
        photo:"assets/t2.PNG",
        date:"29 min ago",
        userId:4,
        likes : 128,
        comments: "6comments",
    },
    {
        id:5,
        desc:"Sunday Morning",
        photo:"assets/kat.PNG",
        date:"33 min ago",
        userId:5,
        likes : 628,
        comments: "69comments",
    },
    {
        id:6,
        desc:"Sunday Morning",
        photo:"assets/trio.PNG",
        date:"40 min ago",
        userId:6,
        likes : 928,
        comments: "49comments",
    },
    {
        id:7,
        desc:"Sunday Morning",
        photo:"assets/m.PNG",
        date:"40 min ago",
        userId:7,
        likes : 528,
        comments: "39comments",
    },
    {
        id:8,
        desc:"Sunday Morning",
        photo:"assets/r.PNG",
        date:"48 min ago",
        userId:8,
        likes : 108,
        comments: "29 comments",
    },
    {
        id:9,
        desc:"Sunday Morning",
        photo:"assets/v2.JPG",
        date:"51 min ago",
        userId:9,
        likes : 328,
        comments:" 19comments",
    },
    {
        id:10,
        desc:"Sunday Morning",
        photo:"assets/m2.PNG",
        date:"5 hours ago",
        userId:10,
        likes : 128,
        comments: "6 comments",
    },
    {
        id:11,
        desc:"Sunday Morning",
        photo:"assets/4r.PNG",
        date:"5 hours ago",
        userId:11,
        likes : 1128,
        comments: "66 comments",
    },
  
    {
        id:12,
        desc:"Sunday Morning",
        photo:"assets/v3.PNG",
        date:"5 hours ago",
        userId:12,
        likes : 1128,
        comments: "60 comments",
    },
  
    {
        id:13,
        desc:"Sunday Morning",
        photo:"assets/a.jpg",
        date:"5 hours ago",
        userId:13,
        likes : 528,
        comments: "43 comments",
    },
  
]